apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- range .Values.environment.secrets }}
  {{ .environmentKey }}: {{ .name | b64enc }}
  {{- end }}
