apiVersion: v1
kind: Service
metadata:
  name: {{ include "test.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "test.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
