{{- if and $.Values.ingress.enabled (eq $.Values.ingress.scheme "external") }}
{{- if .Capabilities.APIVersions.Has "networking.gke.io/v1" }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "test.fullname" $ }}-external-ingress-cert
  namespace: {{ $.Release.Namespace }}
spec:
  domains:
    - {{ $.Values.externalIngress.host }}
{{- end }}
{{- end }}
