{{- if .Capabilities.APIVersions.Has "networking.gke.io/v1" }}
{{- range .Values.externalIngress.configs }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "test.fullname" $ }}-external-ingress-cert
  namespace: {{ $.Release.Namespace }}
spec:
  domains:
    - {{ .host }}
{{- end }}
{{- end }}