{{- if .Values.image.credential }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ first .Values.imagePullSecrets | pluck "name" | first }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- if eq (default "docker" .Values.image.registry) "docker" }}
    {{- printf "{\"auths\":{\"docker.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}"
        .Values.image.credential.username
        .Values.image.credential.password
        (printf "%s:%s" .Values.image.credential.username .Values.image.credential.password | b64enc) | b64enc }}
  {{- else if eq .Values.image.registry "github" }}
    {{- printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}"
        (.Values.image.credential.password | b64enc) | b64enc }}
  {{- else if eq .Values.image.registry "gitlab" }}
    {{- printf "{\"auths\":{\"registry.gitlab.com\":{\"auth\":\"%s\"}}}"
        (.Values.image.credential.password | b64enc) | b64enc }}
  {{- else }}
    {{- fail "Unsupported registry. Please specify 'docker', 'github', or 'gitlab' in .Values.image.registry." }}
  {{- end }}
{{- end }}
