{{- if .Values.image.credential }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.repository .Values.image.credential.username .Values.image.credential.password (printf "%s:%s" .Values.image.credential.username .Values.image.credential.password | b64enc) | b64enc }}
{{- end }}
