{{- range .Values.externalIngress.configs }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .service }}-{{ .port }}-external-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .service }}-{{ .port }}-external-ingress-ip
    networking.gke.io/managed-certificates: {{ .service }}-{{ .port }}-external-ingress-cert
spec:
  defaultBackend:
    service:
      name: {{ .service }}
      port:
        number: {{ .port }}
{{- end }}

