{{- if .Values.metaEnvironmentFields.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "test.fullname" . }}-agent-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "test.fullname" . }}-agent-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "test.fullname" . }}-agent-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
