{{- if .Values.metaEnvironmentFields.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test.fullname" . }}-agent-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- end }}
