{{- if .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Capabilities.APIVersions.Has "networking.gke.io/v1beta1" }}
    {{- if eq .Values.ingress.scheme "internal" }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- end }}
spec:
  type: NodePort
  selector:
    {{- include "test.labels" . | nindent 4 }}
  ports:
    {{- range .Values.services }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
{{- end }}