{{- if .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    {{- include "test.labels" . | nindent 4 }}
  ports:
    {{- range .Values.services }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
{{- end }}