# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Client

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


defaults:
  run:
    working-directory: client


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: client/go.mod
        cache-dependency-path: client/go.sum

    - name: Install templ
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...

