# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Sidecar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


defaults:
  run:
    working-directory: web/sidecar


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: web/sidecar/go.mod
        cache-dependency-path: web/sidecar/go.sum

    - name: Set up Kind
      uses: helm/kind-action@v1

    - name: Build
      run: go build

    - name: Test
      run: go test -v ./...

