# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Sidecar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


defaults:
  run:
    working-directory: web/sidecar

env:
  GKE_PROJECT_ID: context-co
  GKE_ZONE: us-central1
  GKE_CLUSTER_NAME: autopilot-cluster-1

jobs:

  build:
    runs-on: runs-on,runner=16cpu-linux-x64,run-id=${{ github.run_id }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: web/sidecar/go.mod
        cache-dependency-path: web/sidecar/go.sum

    - name: Set up Kind
      uses: helm/kind-action@v1

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Build
      run: go build

    - name: Test
      run: go test -v ./...

